### ISSUE TITLE
[Feature request] Clone case classes and set new values when not knowing exact type.

### ISSUE THREAD

**Issue by cupuyc** [scalalandio/chimney#103]
Typical situation in our project is case classes that share common fields by trait.
```
trait Education {
    def shortName: String
    def years: Int
  }
  
case class School(shortName: String, years: Int) extends Education
case class University(shortName: String, years: Int, finished: Option[Int]) extends Education
```

And a common scenario is where a code knows that variable type is `Education` and needs to modify it.
Straightforward implementation is:
```
def withUpdatedShortName(newValue: String) : Education = {
    this match {
         case e: School => e.copy(shortName = newValue)
         case e: University => e.copy(shortName = newValue)
    }
}
```

Now, what I would like to know if this is common scenario for other ones and how chimney DSL and implementation could look like.

**Comment by MateuszKubuszok** [comment]
Provided that this trait is `sealed` it is possible with newest 1.0.0-RC1 release - see [scastie](https://scastie.scala-lang.org/fBxh4pYFT3iXBIySp9r7Dg).
