### ISSUE TITLE
Ability to use dsl inside Transformer definition

### ISSUE THREAD

**Issue by REDNBLACK** [scalalandio/chimney#105]
I want to define transformation logic in separate objects, but i also want to use transformation dsl inside of Transformer definition. Currently this piece of code gives StackOverflow.

```
import io.scalaland.chimney.dsl._
import io.scalaland.chimney.Transformer

object Run extends App {
  case class Foo(a: String, b: Int, c: Int)
  case class Bar(a: String, b: Int, x: Long)

  object TransformerInstances {
    implicit val fooBarTransformer: Transformer[Foo, Bar] = foo => {
      foo.into[Bar]
        .withFieldComputed(_.x, _.c.toLong)
        .transform
    }
  }

  import TransformerInstances._

  val foo = Foo("a", 1, 3)

  println(foo.transformInto[Bar])
}

```

**Comment by krzemin** [comment]
I am aware of this issue, but I don't know whether it's possible to resolve it properly in the Chimney's implementation.

Briefly, `.transform` call in your instance requires implicit instance of `Transformer[Foo, Bar]` which may be automatically generated by macro, or supplied through implicit scope. In this case, Scala compiler picks `implicit val fooBarTransformer` which is being just defined.

You can work it around by juggling implicit instances, like:

```scala
object TransformerDefinitions {
   val fooBarTransformer: Transformer[Foo, Bar] = foo => {
      foo.into[Bar]
        .withFieldComputed(_.x, _.c.toLong)
        .transform // no implicit Transformer[Foo, Bar] in scope, macro goes in!
    }
}

object TransformerInstances {
  implicit val fooBarTransformer: Transformer[Foo, Bar] =
    TransformerDefinitions.fooBarTransformer // introduce already generated transformer into implicit scope here
}
```

**Comment by nadavwr** [comment]
In Circe it is possible to use a derived `Decoder` in order to define an implicit `Decoder` manually.
This is how they do it:

```scala

case class Exported[+T](instance: T) extends AnyVal

trait LowPriorityDecoderInstances {
  implicit final def importedDecoder[A](
    implicit exported: Exported[Decoder[A]]
  ): Decoder[A] = exported.instance
}

// derivation actually creates `Exported[Decoder[A]]`
trait AutoDerivation {
  implicit def exportDecoder[A]: Exported[Decoder[A]] = macro ExportMacros.exportDecoder[DerivedDecoder, A]
  implicit def exportEncoder[A]: Exported[ObjectEncoder[A]] = macro ExportMacros.exportEncoder[DerivedObjectEncoder, A]
}

// then at usage we can:
case class Foo(a: Int)
object Foo {
  implicit val fooDecoder: Decoder[Foo] = importedDecoder[Foo].prepare(_.downField("bar"))
}
```

I went with Circe's "full auto" mode here. Their "semi auto" spin on this would be a bit more intuitive, since you'd call `deriveDecoder[Foo]` anyway.

**Comment by REDNBLACK** [comment]
@nadavwr @krzemin Working example for anyone interested
[ExportedMacrosChimney.patch.txt](https://github.com/scalalandio/chimney/files/3211631/ExportedMacrosChimney.patch.txt)

**Comment by krzemin** [comment]
This is an interesting proposal indeed. @REDNBLACK could you prepare a PR from your patch?

**Comment by REDNBLACK** [comment]
@krzemin Yeah, but i'm having trouble with sbt and Intellij 2019.2 on project refresh. It keeps failing to resolve dependencies, the only workaround is to disable crossProject.

```
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.scala-native#nativelib_native0.3_2.12;0.3.8: not found
[error] unresolved dependency: org.scala-native#javalib_native0.3_2.12;0.3.8: not found
[error] unresolved dependency: org.scala-native#auxlib_native0.3_2.12;0.3.8: not found
[error] unresolved dependency: org.scala-native#scalalib_native0.3_2.12;0.3.8: not found
[error] unresolved dependency: org.scala-native#test-interface_native0.3_2.12;0.3.8: not found
[error] unresolved dependency: org.scala-native#nscplugin_2.12.8;0.3.8: not found
```

**Comment by krzemin** [comment]
@REDNBLACK You can work it around by commenting out `NativePlatform`, `chimney.native` and other native settings in `build.sbt`, then import to IntelliJ, but not committing changes from this file.

**Comment by ulanzetz** [comment]
https://github.com/scalalandio/chimney/pull/112 is alternative variant to solve this

**Comment by rolandjohann** [comment]
Wanted to state that Transfomer derivation via `Transformer.derive[A, B]` leads to `StackOverflowError` as well

**Comment by krzemin** [comment]
Last few days me and @MateuszKubuszok were trying to fix this issue with `Exported` instances as it was suggested, but we've found out that wanting to support 2 base use cases (use already defined instances and using dsl inside transformer definition) was simply impossible, as we ended up referring to the same instance being defined, regardless if it was wrapped in `Exported` or not.

We propose #129 which is another proposal which addresses this issue (and more).
