### ISSUE TITLE
Enable .withField*** when writing to Java bean

### ISSUE THREAD

**Issue by krzemin** [scalalandio/chimney#110]
There's a limitation (https://scalalandio.github.io/chimney/#Limitations) that you can't provide values for missing fields when writing to Java bean.

The task is to find out whether we can make `.withFieldConst`, `.withFieldComputed` and `.withFieldRenamed` effective for Java beans too.

**Comment by MateuszKubuszok** [comment]
Resolved on branch `scala-3` (https://github.com/scalalandio/chimney/pull/325).
