### ISSUE TITLE
Compiler hangs if CC has 37 fields

### ISSUE THREAD

**Issue by maciejbak85** [scalalandio/chimney#111]
Hi,

I have case class with 37 fields,
I was using 
```
this.into[ArticleToImport]
.withFieldComputed(_.a, _ => a)
```
`withFieldComputed `for 20 fields.
Intellij showed me that during phase silencer on this file it was hanging.
neither from sbt compile worked.
Ive checked that adding more fields to this CC with chimney caused errors.
No issues when removed few fields or did manually the job.

**Comment by krzemin** [comment]
Hi, thanks for reporting. I was trying to reproduce it as you have described on a minimal example, but I failed. Could you please post case class definitions along with your exact transformation chain (`withField***`) or even failing test?

**Comment by krzemin** [comment]
Just realized that `silencer` is not standard scalac phase, it comes from https://github.com/ghik/silencer. Please report there if the issue still persist.
