### ISSUE TITLE
Type check bug: shouldn't compile but it does

### ISSUE THREAD

**Issue by davojan** [scalalandio/chimney#117]
In the following code chimney can't know how to convert ``groups: Option[Seq[GroupPatchInput]]`` into ``Option[GroupsPatchProto]``. But in compiles fine.

```scala
import io.scalaland.chimney.dsl._

object Test {

  // input
  case class CampaignPatchInput(
    id: Option[Int],
    groups: Option[Seq[GroupPatchInput]],
  )

  case class GroupPatchInput(id: Option[Int])

  // proto
  final case class CampaignPatchProto(
    id: Int = 0,
    groups: Option[GroupsPatchProto] = None,
  )

  final case class GroupsPatchProto(
    patches: Seq[GroupPatchProto] = Seq.empty,
  )

  final case class GroupPatchProto(
    id: Int = 0,
    // it compiles even if we uncomment this ``name`` field
    // but it shouldn't even without it
    // name: String,
  )

  def inputToProto(input: CampaignPatchInput): CampaignPatchProto =
    input.into[CampaignPatchProto]
      .withFieldComputed(_.id, _.id.getOrElse(0))
      .transform
}
```

```
scalaVersion in ThisBuild := "2.12.9"
"io.scalaland" %% "chimney" % "0.3.2"
```

**Comment by krzemin** [comment]
Hi @davojan. Sorry for not answering for such a long time - I was extremely busy recently.

It may seem a little bit counter-intuitive, but in your example you have default values provided for each field. According to [documentation](https://scalalandio.github.io/chimney/#Defaultvalues), when Chimney can't derive transformer basing on source type structure, but target field has default value in definition, it will be used. You can disable this behavior by calling `.disableDefaultValues` - then code will not compile pointing out to a place where there's a type mismatch:

```
[error] io.scalaland.chimney.IssuesSpec.GroupsPatchProto
[error]   patches: scala.collection.immutable.Seq - no accessor named patches in source type scala.collection.immutable.Seq
[error] 
[error] Consult https://scalalandio.github.io/chimney for usage examples.
[error] 
[error]           .transform
[error]            ^
[error] one error found
```

**Comment by davojan** [comment]
Hi @krzemin. Thanks for your clarification. Now I got the idea, but this behaviour is definitely conter-intuitive. In my opinion default values should be used only in case when there is no field with the same name in the source object. Consider this example:

```scala
case class Source(a: String, b: Int)
case class Dest(a: String, b: Double = .0, c: Option[Boolean] = None)

Source("some string", 10)
  .into[Dest]
  .withFieldComputed(_.b, _.b.toDouble)
  .disableDefaultValues
  .transform
```

We can't have field `c` auto-filled with default value without additional boilerplate.

I would say, that current behavior should be explicitly enabled if it is required, because it's more error-prone.

**Comment by krzemin** [comment]
> In my opinion default values should be used only in case when there is no field with the same name in the source object.

I think this is exactly current behavior. Consider these 2 examples:

```scala
Source("some string", 10)
  .into[Dest]
  .transform

// io.scalaland.chimney.IssuesSpec.Dest
//   b: scala.Double - can't derive transformation from b: scala.Int in source type io.scalaland.chimney.IssuesSpec.Source
```

Default value for `c` could be used, but compilation fails as there is some field (`b: Int`) with the same name in source object, but type is different and we cannot directly construct target value. Despite target field has default value (`b: Double = .0`), it's not used.

```scala
Source("some string", 10)
  .into[Dest]
  .withFieldComputed(_.b, _.b.toDouble)
  .transform
// it computes to  Dest("some string", 10.0, None)
```

If you provide a way how to compute `b: Double`, but without disabling default values, only `c` will get the value from a default value. Note you could achieve the same behavior without using `withFieldComputed`, but defining implicit transformer between Int and Double:
```scala
implicit val intToDouble: Transformer[Int, Double] = _.toDouble
```
