### ISSUE TITLE
Transformation returning Validated/Either/...

### ISSUE THREAD

**Issue by sideeffffect** [scalalandio/chimney#118]
Would it be possible to have a slightly different variant of `TransformerInto.enableUnsafeOption`, which instead of throwing exceptions would return a value, like `cats.data.Validated` (or something analogous, like `Either`).

Our use case is that we would like to convert ScalaPB generated case classes (where everything is `Option`al) to our domain case classes where some fields are mandatory. It would help us a lot, if the convertor method returned just a plain value (Validated, Either,...) instead of throwing and us having to catch the exceptions.

It would behave similar to [`henkan`](https://github.com/kailuowang/henkan#transform-between-case-classes-with-optional-field) which also has `validate` method to return `cats.data.Validated`.

**Comment by MateuszKubuszok** [comment]
https://github.com/scalalandio/chimney/pull/146 implements what you described, but before we decide to merge and release it, it would be good if more eyes looked at it and maybe tested their use cases.

**Comment by MateuszKubuszok** [comment]
Feature released in 0.5.0, available on OSS Sonatype, should appear on Maven soon.
