### ISSUE TITLE
Don't use fields or methods by default?

### ISSUE THREAD

**Issue by jatcwang** [scalalandio/chimney#128]
```
object Test {

  import io.scalaland.chimney.dsl._

  case class Boo(i: Int, s: String) {
    def d: Double = 5
  }

  case class Foo(i: Int, s: String, d: Double)

  Boo(1, "").into[Foo].transform

}
```

This compiles on version 0.3.5, but doesn't feel like it should. Should we only consider case class constructor fields for automatic field mapping?

**Comment by krzemin** [comment]
It was added explicitly in #67 in order to be able to read from non case classes.

Any arguments why it shouldn't be the default?

**Comment by jatcwang** [comment]
Methods can be side-effecting and the user will not see the problem until it's too late. 
IMO by default only public `val`s fields should be used - it's the safe default. (No private[..] or protected even if it's visible in the given scope) 

From what I can gather, JS facade types can have `val`s as well. Will this break them?

**Comment by krzemin** [comment]
As long as we can detect public vals using compile-time reflection API, I'm OK with making this behavior opt-in: disabled by default, but enabled using special operation in DSL.

**Comment by jatcwang** [comment]
Cool I'll give it a go :)

**Comment by krzemin** [comment]
Go ahead 👍

**Comment by danslapman** [comment]
Another terrible example is mapping Vector[T] into Option[NonEmptyList[T]], NonEmptyList is defined as `final case class NonEmptyList[+A](head: A, tail: List[A])` in cats, and chimney tries to find `head` & `tail` field. Unfortunately, methods with such names exists in Vector causing empty case fail at runtime

**Comment by krzemin** [comment]
@jatcwang thank you for contribution.
