### ISSUE TITLE
Enhanced error reporting for lifted transformers

### ISSUE THREAD

**Issue by krzemin** [scalalandio/chimney#153]
Currently in lifted transformers user is responsible for creating invalid case of `F[To]`, which most likely ends up like:

```scala
.withFieldComputedF(_.field, source => parse(source.field) match {
  case valid =>
    // construct F[To] based on valid
    Validation.valid(valid)
  case invalid =>
    // pack <invalid> case to F[To], with any eventual error info from `source`
    Validation.invalid(NEC.one(s"${source.id}: invalid!"))
})
```

Despite having `source` available in context brings a possibility to provide more detailed error information, this approach has some disadvantages:
1. wrapping into `F` needs to be done manually each time (`Validation.invalid(NEC.one(<error message comes here>))`), while only error message is relevant here
2. it does not provide detailed context information (i.e. path to concrete object in the source entity) in case this transformation is re-used in outer one

In #145 there was prototype implementation of enhanced error reporting which addressed (2).

We need to explore possibilities on how to enhance API in a compatible way in order to address both issues.

**Comment by ulanzetz** [comment]
Maybe add new typeclass . Something like this:
```
trait TransformerFErrorSupport[F[+_]] {
  def error[A](message: String): F[A]
  
  def addPrefix[A](fa: F[A], prefix: String): F[A]
}
```
Add implements it for Validated[S[TransformationError]] where S is semigroup and TransformationError is something like this:
```
abstract class TransformationError(val message: String) {
  def errorPath: Chain[String]

  def addPrefix(prefix: String): TransformationError
}

object TransformationError {
  private case class Deep(override val message: String, path: NEC[String]) extends TransformationError(message) {
    lazy val errorPath: Chain[String] =
      path.toChain

    def addPrefix(prefix: String): TransformationError =
      Deep(message, path.prepend(prefix))
  }

  private case class Root(override val message: String) extends TransformationError(message) {
    val errorPath: Chain[String] =
      Chain.nil

    def addPrefix(prefix: String): TransformationError =
      Deep(message, NEC(prefix))
  }

  def apply(message: String): TransformationError =
    Root(message)
}
```

Then we can find optional instance of TransformerFErrorSupport in expanding TranformerF for case class and add error path, if typeclass found

Also we can add syntax with withFieldComputedF, if typeclass found

**Comment by sideeffffect** [comment]
Great news indeed! :tada: 
Will there be a release soon that will contain this feature?

**Comment by krzemin** [comment]
@sideeffffect Yes, there should be - most likely over the weekend.
