### ISSUE TITLE
Complete test suite for protocol buffers

### ISSUE THREAD

**Issue by krzemin** [scalalandio/chimney#18]
The idea is to:
- configure [scalaPB](https://github.com/scalapb/ScalaPB) to be run only on test configuration
- define simple example protocol with (possibly) all supported PB data types - case classes should be automatically generated by scalaPB
- define corresponding domain in scala world, but with value classes instead of primitives
- write tests that check conversion round trips for many various instances

It probably includes #7 to complete (pb enums are like sealed hierarchies, but with non-total mapping, we'll need to think about it).

@MateuszKubuszok WDYT?

**Comment by MateuszKubuszok** [comment]
@krzemin nifty, idea. I like it. I am afraid though that https://github.com/scalalandio/chimney/issues/19 is a blocker.

**Comment by krzemin** [comment]
It was basically done.
