### ISSUE TITLE
Combination of supported features fails to compile

### ISSUE THREAD

**Issue by MateuszKubuszok** [scalalandio/chimney#19]
I have a test case during entity initialization that goes like this:

    case class NewEntity(name: Option[String])
    case class Entity(id: Long, name: Option[String], isDeleted: Boolean)

    NewEntity(Some("name")).into[Entity]
        .withFieldConst('id, 0L)
        .withFieldConst('isDeleted, false)

I think we can start working on it in `feature/feature-combination ` where I added the test case.

**Comment by krzemin** [comment]
Fixed with #22
