### ISSUE TITLE
Transform through method other than default constructor

### ISSUE THREAD

**Issue by Krever** [scalalandio/chimney#192]
Instead of using the default constructor, we could use an alternative method specified by the user. Typically some version of `apply`.

The API could look like `into[Foo].via(Foo.apply).transform` or sth similar.

**Comment by taeguk** [comment]
It will be very useful. Any plans about this? 🙏

**Comment by mariussoutier** [comment]
This would be really nice in order to use a companion object's apply method.

**Comment by MateuszKubuszok** [comment]
Released in 0.8.4
