### ISSUE TITLE
Fallback on existing target

### ISSUE THREAD

**Issue by MateuszKubuszok** [scalalandio/chimney#20]
Imagine case when I have public API model and internal model:

    case class ApiModel(name: Name, surname: Surname)
    case class DomainModel(id: Id, name: Name, surname: Surname, additionalData: AdditionalData)

when I receive ApiModel from the outside I would like data to be moved to a new DomainModel - but properties not overridden by the update could be taken from existing instance, e.g.:

    apiModel.into[DomainModel].fallbackOn(existingModel).transform

@krzemin WDYT?

**Comment by krzemin** [comment]
I think that #28 mostly addressed that, but with different type class and syntax (called patching).
