### ISSUE TITLE
Usage of tags can break derivation

### ISSUE THREAD

**Issue by MateuszKubuszok** [scalalandio/chimney#21]
Test case:

```
object TestConversion {
  import io.scalaland.chimney.dsl._
  import shapeless.tag
  import shapeless.tag._

  sealed trait Tag

  final case class Input(
    long:   Long @@ Tag,
    string: String
  )

  final case class Output(
    long: Long @@ Tag
  )

  val test = Input(tag[Tag](0L), "").transformInto[Output]
}
```

results in `Could not find implicit for derivedTransformer...`

**Comment by MateuszKubuszok** [comment]
I we remove tag OR if we remove `string` param OR if we replace `long` with `string` in `Output` class derivation succeeds.

**Comment by MateuszKubuszok** [comment]
@krzemin investigated the issue and found out it is a problem described in https://github.com/milessabin/shapeless/pull/726 - if we figured that one out we could fix the issue.

**Comment by krzemin** [comment]
If this is the only dependent issue, then it should work under 2.11. Unfortunately, we don't support 2.11 atm :)

**Comment by krzemin** [comment]
As we now support 2.11, I tried it and confirm it works on 2.11 with no problems.
