### ISSUE TITLE
A way to convert between ScalaPB enum

### ISSUE THREAD

**Issue by Lagawrd** [scalalandio/chimney#217]
`enum Some {
    OPTIONA = 0;
    OPTIONB = 1;
    OPTIONC = 2;
}`

`enum SomeOther {
    OPTIONA = 0;
    OPTIONB = 1;
    OPTIONC = 2;
}`

I am currently not able to do something like `Some.transformInto[SomeOther]`.  It errors out with being ambiguous.

I tried writing my own implicit class to deal with identical/similar enum attributes but I am not able to since `GeneratedEnumCompanion` and `GeneratedEnum` are traits.

**Comment by krzemin** [comment]
It seems like the same issue as #210, which was resolved in #261.
Please reopen if it still persist.
