### ISSUE TITLE
Bump sphinx version

### ISSUE THREAD

**Issue by lbialy** [scalalandio/chimney#220]
Chimney depends on sphinx version = 3.1.2, current sphinx is 5.0.2 and fails with chimney docs.

**Comment by MateuszKubuszok** [comment]
@lbialy I added workaround to README, which let you build things locally with Docker rather than fighting Python and package managers.

**Comment by MateuszKubuszok** [comment]
Since we migrated to ReadTheDocs this is no longer needed :)
