### ISSUE TITLE
Transformation to a case class with two parameters list 

### ISSUE THREAD

**Issue by rgugliel-da** [scalalandio/chimney#224]
Hello!
Let's say I have two case classes:
```
final case class Source(a: Int)
final case class Target(a: Int)(b: String)
```

Is there a way to define a transformer from Source to Target (and provide the default value for `b`)?

Thanks!

**Comment by lbialy** [comment]
Hey!

First of all - you really shouldn't be using case classes this way. Are you aware of the issues with all the generated methods like `hashCode` and `equals` that multiple parameter lists introduce? 

This for instance does not throw:
https://scastie.scala-lang.org/1mRLxvp8R6uoRgMBfJ0XPA

There are currently no plans to support this. What is your use case? Do you absolutely need curried (case) classes?

**Comment by rgugliel-da** [comment]
Hi @lbialy ,
Thanks for your answer. I have in my second parameters list exactly parameters that should not be taken into account when doing comparisons. I could also change the `equals` but then there is the risk of forgetting to update this method when I add a new attribute in the future.

**Comment by lbialy** [comment]
I'm not sure this is a feature chimney should support given how obscure and quirky thing case classes with multiple parameter lists are. Do you have a usable workaround that uses chimney in any way?

**Comment by rgugliel-da** [comment]
Yes, I agree, this is non-standard and one should be careful with these. Nope, I did not succeed to make it work with chimney unfortunately.
But no worries, I understand!
