### ISSUE TITLE
Internal code refactor and API simplicifaction

### ISSUE THREAD

**Issue by MateuszKubuszok** [scalalandio/chimney#239]
Currently, the internals got complicated and hard to maintain. If we want to be able to support this library certain simplifications and refactoring will be necessary.

For version 0.7.0 we might provide API necessary to unblock the simplifications:

 * provide a better alternative to lifted transformers (`TransformerF`s) - partial transformers
 * once partial transformers are ready:
   * deprecate `TransformerF`s
   * deprecate `unsafe` options in `Transformer`
 * describe migration-path in documentation
 * create benchmarks to make sure that our new structure is at least as performant as old one

Major work for partial transformers is being done in https://github.com/scalalandio/chimney/pull/235 while benchmarks were kicked-off in https://github.com/scalalandio/chimney/pull/226.

For following versions (possibly 0.8.0):

* remove lifted transformers (`TransformerF`s) and unsafe options
* modify macros to use `Expr[T]` and `Type[T]` (would require tagging `c.universe.Type`) instead of untyped `Tree`s
* introduce an internal structure to model macro-computations and errors which would help us provide better error messanges and macro diagnostics
* extract Scala-version-macro specific code from the logic that could be shared between Scala 2 and Scala 3

Migration for DSL-related macros was researched in https://github.com/jchyb/chimney/tree/scala-3-migration while ways of sharing logic between macros and internal structure for macro errors aggregation was researched in https://github.com/MateuszKubuszok/pipez.

Incorporating these findings would unblock https://github.com/scalalandio/chimney/issues/201 and this issue will be used to trace work preceding #201.

**Currently planned work**:

- [x] migrate `build.sbt` to sbt-projectmatrix and sbt-commandmatrix to enable easy SJS and SN addition, and easy S3 addition - https://github.com/scalalandio/chimney/pull/241
- [x] drop features deprecated in 0.7.0 (LiftedTrasformers and unsafe options)
- [x] migrate tests to MUnit to unblock S3
- [x] reorganize tests to to addres 8kloc of unrelated staff in one suite
- [x] migrate untyped `Tree`s in internal methods to `Type[A]` and/or `Expr[A]`
- [x] introduce separate type for derivation result to make it easier to model orElse, parallel semantics, errors and diagnostics gathering
- [x] separate version-specific macro logic from shared macro logic
- [x] separate version-specific scalac and scaladoc options from shared options
- [x] make macro util `protected`, `private` or `private[internal]` where possible to prevent intellisense pollution

**Comment by krzemin** [comment]
> migrate tests to MUnit to unblock S3

It may no longer be a blocker: utest supports scala 3 since 0.7.10: https://github.com/com-lihaoyi/utest#changelog

**Comment by MateuszKubuszok** [comment]
Done on #320
