### ISSUE TITLE
Improve support for AnyVals

### ISSUE THREAD

**Issue by MateuszKubuszok** [scalalandio/chimney#249]
Currently we are explicitly supporting:

* `case class Foo(t: T) => T` - unwrapping of type without any conversion
* `T => case class Foo(t: T)` - wrapping if type without any conversion

we should also add:

* `case class Foo(t: T) => case class Bar(t: T)` - re-wrapping of type without any conversion
* `case class Foo(s: S) => T` - unwrapping of type when `S => T` conversion exists
* `S => case class Foo(t: T)` - wrapping if type when `S => T` conversion exists
* `case class Foo(s: S) => case class Bar(t: T)` when `S => T` conversion exists

**Comment by ekhov** [comment]
If you're accepting contributions and this feature is not urgent, I'd be happy to try to implement these :)

**Comment by krzemin** [comment]
The whole scope was addressed in #265 👏
