### ISSUE TITLE
How to translate Java Bean To Scala Bean

### ISSUE THREAD

**Issue by Bryce-Loski** [scalalandio/chimney#260]
I used Java Bean to Scala case class was error.
Selector of type entity.Property => Long is not valid: ((x$5: entity.Property) => x$5.getSkuId())
        .withFieldRenamed(_.getSkuId, _.sku_id)

**Comment by Bryce-Loski** [comment]
The Java Bean Write With SpringBoot.

**Comment by MateuszKubuszok** [comment]
Could you provide some more detail? A snippet reproducing the issue would be really helpful.
