### ISSUE TITLE
versionScheme is missing from pom on maven central

### ISSUE THREAD

**Issue by adriaanm** [scalalandio/chimney#263]
**Checklist**
- [x] I checked the https://github.com/scalalandio/chimney/issues and haven't found the issue reported

**Describe the bug**
There is no versionScheme in the published pom on maven central. I noticed the setting got added to the build in #241 -- great! However, something is keeping it from showing up in the published pom.

**Reproduction**
Go to https://repo1.maven.org/maven2/io/scalaland/chimney_2.13/0.7.0/chimney_2.13-0.7.0.pom, confirm the expected `<properties>` (below) are missing. They are present in the pom generated by publishLocal :-)

**Expected behavior**
I expected something like this in the pom:
```
    <properties>
        <info.versionScheme>early-semver</info.versionScheme>
    </properties>
```

**Actual behavior**
The properties are missing in the published pom. Filtered out? I tried to figure it out, but didn't see any obvious issues.

**Which Chimney version do you use**
0.7.0

**Which platform do you use**
- [X] JVM

**Comment by krzemin** [comment]
Hey, thanks for reporting!

It seems that setting version scheme globally using the method below doesn't work.
```
ThisProject / versionScheme := Some("early-semver")
```

> They are present in the pom generated by publishLocal :-)

In my case they were missing for both `publishLocal` and `publishSigned`. After setting manually in #264 they are present when generating with both commands. I hope it should fix the issue.
