### ISSUE TITLE
Refactor `TransformerMacros` into rule-based, cross-compilable architecture

### ISSUE THREAD

**Issue by krzemin** [scalalandio/chimney#276]
Scala 2 chimney dispatches transformation rules as a single if-then-else block inside `TransformerMacros` module.

In the scope of this task we should:
- define an interface that can express transformation rules
- rewrite existing transformation logic in terms of independent rules which should end up in separate files
- make sure the rules can call derivation logic recursively
- new logic should call cross-compilable metaprogramming abstractions so that they generate semantically-equivalent code for both Scala 2 and 3

Rules to cover (names following existing Scala 2 impl):
- [x] `expandSubtypes` - implemented in https://github.com/scalalandio/chimney/pull/296 to verify that it works
- [x] `expandOptions` - https://github.com/scalalandio/chimney/issues/303
- [x] `expandPartialFromOptionToNonOption` - https://github.com/scalalandio/chimney/issues/305
- [x] `expandTargetWrappedInOption` - https://github.com/scalalandio/chimney/issues/305
- [x] `expandSourceWrappedInOption` - https://github.com/scalalandio/chimney/issues/306
- [x] `expandValueClassToValueClass` - https://github.com/scalalandio/chimney/issues/307
- [x] `expandValueClassToType` - https://github.com/scalalandio/chimney/issues/308
- [x] `expandTypeToValueClass` - https://github.com/scalalandio/chimney/issues/309
- [x] `expandEithers` - https://github.com/scalalandio/chimney/issues/310
- [x] `expandFromMap` - https://github.com/scalalandio/chimney/issues/311
- [x] `expandIterableOrArray` - https://github.com/scalalandio/chimney/issues/312
- [x] `expandDestinationTuple` - https://github.com/scalalandio/chimney/issues/313
- [x] `expandDestinationCaseClass` - https://github.com/scalalandio/chimney/issues/314
- [x] `expandDestinationJavaBean` - https://github.com/scalalandio/chimney/issues/315
- [x] `expandSealedClasses` - https://github.com/scalalandio/chimney/issues/316

**Comment by MateuszKubuszok** [comment]
Merged to `scala-3` in #320.
