### ISSUE TITLE
Use typed abstractions in macros

### ISSUE THREAD

**Issue by MateuszKubuszok** [scalalandio/chimney#279]
Currently we use a lot of `c.universe.Type` and `c.universe.Tree` inside macros which would make cross-compilation with 3 hard.

For shared code, we create abstract types `Type[T]` and `Expr[T]` and use them for passing data around [like here](https://github.com/MateuszKubuszok/pipez/blob/master/pipez/src/main/scala/pipez/internal/Definitions.scala#L21).

But a prerequisite for that is using typed abstractions instead of untyped in the first place. We could define them [like here](https://github.com/MateuszKubuszok/pipez/blob/master/pipez/src/main/scala-2/pipez/internal/PlatformDefinitions.scala#L18).

This would be helpful in #276 .

**Comment by krzemin** [comment]
Cross-compilable typed abstractions were delivered in #286.
