### ISSUE TITLE
Compiler warning when using partial transformers

### ISSUE THREAD

**Issue by pierangeloc** [scalalandio/chimney#287]
**Checklist**
- [x] I read the documentation at https://scalalandio.github.io/chimney/ and checked that the functionality exists
- [x] I verified that the behavior for my use case doesn't match the documentation
- [x] I checked the https://github.com/scalalandio/chimney/issues and haven't found the issue reported
- [x] I confirmed that the bug is not related to functionality that was deprecated: lifted transformers (`TransformerF`s) or `unsafeOption` flags

**Describe the bug**
When using partial transformers, the compiler throws warnings like ` fruitless type test` 

**Reproduction**
https://scastie.scala-lang.org/pierangeloc/9ZXRGxT9QzyZU62NBbhhxA/8

**Expected behavior**
Compiler should not throw warnings

**Actual behavior**
Compiler says
```fruitless type test: a value of type io.scalaland.chimney.partial.Result.Value[String] cannot also be a io.scalaland.chimney.partial.Result.Errors```

**Which Chimney version do you use**
0.7.1

**Which platform do you use**
- [x] JVM
- [ ] Scala.js
- [ ] Scala Native

**If you checked JVM**
openjdk version "17.0.3" 2022-04-19

**Additional context**
.

**Comment by krzemin** [comment]
It was already fixed in https://github.com/scalalandio/chimney/pull/278

Will be part of the next release.
