### ISSUE TITLE
Document Chimney internals

### ISSUE THREAD

**Issue by MateuszKubuszok** [scalalandio/chimney#302]
Once https://github.com/scalalandio/chimney/issues/276 and https://github.com/scalalandio/chimney/issues/301 are implemented, the mechanics behind Chimney derivation could be documented.

By documentation I mean:

- [ ] documenting the purpose, use cases and behavior of things like: `TransformerContext`, `DerivationResult` `DerivedExpr`, etc as ScalaDoc comments
- [ ] documenting workarounds and all not so straightforward solutions in the platform-specific code to explain _why_ it was done this way as inline comments
- [ ] creating `DESIGN.md` describing Chimney internals
   - [ ] how `.into[]...transform` creates an expression and `TypeClass.define.derive` creates a type class
   - [ ] which parts happen in compile time and which in runtime, how constants and functions are stored and extracted
   - [ ] general idea behind derivation-rule-based-architecture with some examples of the rules (and notice that the exact list of rules will evolve over the time and might be different for each Scala/platform so sourcecode should be the only source of through about them)
   - [ ] in the above, mention how recursive derivation works, how summoning works, that there are priorities to summoning in PartialTransformers etc
   - [ ] how Patchers biggyback on Transformers

This would serve both us, to write down our decisions and rationales behind them, as well as a help to future contributors.

**Comment by krzemin** [comment]
> creating section in Chimney documentation about Chimney internals 

Suggest keeping it out of the user facing docs. Let's have another file like `DESIGN.md` for such internal stuff.
