### ISSUE TITLE
Cross-publish for Scala 2.11.9 and later

### ISSUE THREAD

**Issue by PaulAtBanno** [scalalandio/chimney#31]
Since [SI-7046 is resolved in Scala 2.11.9 or later](https://issues.scala-lang.org/browse/SI-7046), could you please cross-publish for it?

**Comment by krzemin** [comment]
Yes, that should be easily possible. Probably the only thing we have to do before is to replace instances written in SAM-style to portable ones.

**Comment by krzemin** [comment]
Version 0.1.4 is published for 2.11 as well.
