### ISSUE TITLE
"Coming from ..." sections in the documentation

### ISSUE THREAD

**Issue by MateuszKubuszok** [scalalandio/chimney#350]
It would be useful if we created in cookbook sections explaining how to use Chimney if someone has an experience in another library. What comes to mind:

 * [Automapper](https://docs.automapper.org/en/stable/) (C#/.Net)
 * [MapStruct](https://mapstruct.org/) (Java)
 * ~[Scala Automapper](https://github.com/bfil/scala-automapper) (Scala)~
 * ~[Henkan](https://github.com/kailuowang/henkan) (Scala)~
 * ~[Ducktape](https://github.com/arainko/ducktape/) (Scala)~
 * [Bastion](https://github.com/scarisey/bastion) (Scala)
 * [Express Mapper](https://expressmapper.org/) (C#)
 * [Copier](https://github.com/jinzhu/copier) (Go)

They should highlight:

 * what are Chimney counterparts to other libraries options
 * what options are missing in Chimney and if there are some workarounds
 * what options Chimeny has which are missing the the other library

There are also other frameworks like https://www.baeldung.com/java-performance-mapping-frameworks

**Comment by krzemin** [comment]
There's also Swift one: https://github.com/wickwirew/Converter

**Comment by MateuszKubuszok** [comment]
Another one in Scala - https://github.com/btlines/fluent

**Comment by MateuszKubuszok** [comment]
Shapeless for JavaBeans - https://github.com/limansky/beanpuree - `JavaTypeMapper[J, S]` can be compared to transformer with `.enableBeanGetters` and `.enableBeanSetters`

**Comment by MateuszKubuszok** [comment]
I think the most important libraries are covered, so there's no point in keeping the number of open tickets higher, but if there's a new improvement, it could still be linked to this issue.
