### ISSUE TITLE
Support for Proto3

### ISSUE THREAD

**Issue by pchen-nd** [scalalandio/chimney#62]
In protobuf 3, every message field now is made optional. It will be nice that Chimney could make this work:

case class Foo(x: Option[String], y: Option[Int])
case class Bar(x: String, y: Int, z: Boolean = true)

Foo(Some("abc"), Some(10)).transformInto[Bar]

**Comment by krzemin** [comment]
What output would you expect when fields are set to `None`, i.e.:

`Foo(None, None).transformInto[Bar] = ?`

**Comment by pchen-nd** [comment]
Ah...excellent question. 

Okay, I can see a few possibilities. If the type in Option is reference, None could be translated to null, unless there is a default value in the destination field. I know null is considered a bad thing in Scala. So, if Chimney could allow user to customize this behavior (advanced use), say throw a runtime exception instead of automatically converting to null (this is not bad, for lack of "requried field" in proto3, having server side throwing an exception back to caller seems to be reasonable thing. This policy can be a global policy or/and a policy per field. 

For non reference type (Int, Long, Double, Float etc), maybe we could throw runtime exception unless defaults are provided.

BTW, I'm shocked how quick the response comes back :-)

**Comment by krzemin** [comment]
I'm not convinced to propagate support for runtime exceptions or nulls. General rule I'm trying to keep is that the library generates type-safe transformations. Following the principle, it may be possible, to define DSL modifier (or even separate transformation type-class, don't know yet) that returns optional target object. So that:

```
Foo(None, None).transformIntoOpt[Bar]: Option[Bar] == None
Foo(None, Some(10)).transformIntoOpt[Bar]: Option[Bar] == None
Foo(Some("abc"), Some(10)).transformIntoOpt[Bar]: Option[Bar] = Some(Bar("abc", 10, true))

// but the following will not compile unless you explicitly provide values for non-optional target fields 
Foo(Some("abc"), Some(10)).transformInto[Bar]: Bar = ?
```

It's also possible to require default parameters or optional fallback value for each such `Option[T] => T` field transformation in usual transformer DSL:

```
val foo2bar: Foo => Bar = (_: Foo)
  .into[Bar]
  .withOptionFallback(_.x, "xyz")
  .withOptionFallback(_.y, 0)
  .transform

foo2bar(Foo(Some("abc"), Some(10))) = Bar("abc", 10, true)
foo2bar(Foo(None, None)) = Bar("xyz", 0, true)
```

Notice that both proposals are orthogonal.

**Comment by pchen-nd** [comment]
I fully understand why you're insisting on type safeties. Personally I think dynamic exception has its own merits in certain use cases--Scala also has good language support for dealing with exceptions. Data is inherently a dynamic thing. For example, in the first proposal, both "Foo(None, None) & Foo(None, Some(10))" are resulted in "None". User would has noway of knowing the differences (this is a "silent failure" issue: was there no x or was there no y?). A dynamic exception with clear error message can be very helpful. 

That said, I fully respect your principle and I really like your proposals as well. I think you are very much right that two proposals are orthogonal. Each has its own use cases, serves slightly different purpose.

A slight variation of the 1st proposal is, instead of using Option, maybe a different disjunction?  Try/Either or even Scalaz \/?

The 2nd proposal seems to be more flexible, it allows user to customize handling of each field. Hence it might be very useful in transforming proto3 messages (with every field is an Option) to domain objects (where fields could be an Option, but more likely a regular type). I might be wrong, but I think the 2nd proposal covers the cases that I was talking about earlier (minus exception). Basically, the fallback is some kind of default value, it can also be "null" (for reference type) if user chose so?

One more complication is that proto messages could be hierarchical with nested structure, with Option in the nested structure as well. While this is not new to existing implementation, with Option, it brings up potential new challenges.

Thank you again for creating this utility and it tacks an important issue in SW engineering.

**Comment by krzemin** [comment]
> I might be wrong, but I think the 2nd proposal covers the cases that I was talking about earlier (minus exception). Basically, the fallback is some kind of default value, it can also be "null" (for reference type) if user chose so?

Well, it depends on evaluation strategy of fallback parameters. If we manage to keep by name semantics, it'd be possible even to throw an exception in exact place where provided fallback expression was meant to be used.

**Comment by krzemin** [comment]
As pointed out by @Krever in #90, you can easily achieve unsafe `Option[T] => T` transformation by defining following implicit rule in scope:

```
implicit def getByDefault[T]: Transformer[Option[T], T] = (x: Option[T]) => x.get
```

This obviously throws when `x == None`, but you can customize behavior pretty well (`.getOrElse(null)` or even thrown own, more specific exception) if this is what you need.

**Comment by jrduncans** [comment]
I would love to see the `.transformIntoOpt[Bar]` supported. Then you can easily yourself satisfy use cases like filtering out the None's from a list/stream to skip data missing required fields, or throw an exception with `.getOrElse` if you really want, or raise errors in some other way depending on your code patterns.

The `.withOptionFallback` proposal is also cool, but I haven't had a need yet, and seems like it could be done with a Transformer.

**Comment by krzemin** [comment]
As #116 is merged and documented [here](https://scalalandio.github.io/chimney/#Mappingproto3types), I believe we can close this one.
