### ISSUE TITLE
Support for coproducts

### ISSUE THREAD

**Issue by krzemin** [scalalandio/chimney#7]

**Comment by krzemin** [comment]
Another important part of coproduct support was introduced with this commit:
https://github.com/scalalandio/chimney/commit/7b34f7aeebe7a22903b1d5d24f5fd53cee8358ca

@MateuszKubuszok  Do we need to support anything else?

**Comment by MateuszKubuszok** [comment]
I don't think we need anything else at-the-moment. We might reconsider later on.
