### ISSUE TITLE
Change base package to chimney?

### ISSUE THREAD

**Issue by kubukoz** [scalalandio/chimney#72]
With syntax-heavy libraries it usually helps a lot to have a shorter implicit. Currently with Chimney I find myself doing `import io.scalaland.chimney.dsl._` a lot, but what I'd really like to do is just `import chimney.implicits._` or `chimney.dsl._`.

I suggest renaming the base package in a future release (maybe by introducing a type alias to the old package, or move everything and have deprecated type aliases pointing to the new package).

**Comment by krzemin** [comment]
I like the proposal, let's do that!

**Comment by zarthross** [comment]
I'm not really a fan of this idea, in my experience it increases the likelihood of namespace collisions. 

For example, if I have some helper functions i want to add to chimney, i might make a package `me.helpers.chimney` along with some helpers for `cats` and other libs. If I came along and imported `me.helpers._`  and then after that import imported your `chimney.dsl._`... the second import is NOT chimney, but my `me.helpers.chimney`... i'd have to either correct the order, or add `_root_` to the front of `chimney.dsl._` 

Also, Intellj does NOT play nice with that.  
So, while its a bit inconvenient to have to type the extra, and I understand ones motivations, I'm not in favor.

My 2 cents....

**Comment by kubukoz** [comment]
Cats has a top-level cats package, how is that different?

**Comment by zarthross** [comment]
It's no different.  It has the same problem.

**Comment by kubukoz** [comment]
@krzemin what do you think would be the best direction? Follow up with this, or close? @zarthross has a point :P

**Comment by krzemin** [comment]
Recently I jumped into similar problems as @zarthross describes. Hopefully in scala we have `_root_` imports, but this is more annoying than having longer package names. I suggest to close it then.
Anyway, in your project you can still define package object with type aliases if it's not problem for you.

**Comment by kubukoz** [comment]
I'll close then. It's probably the best choice :)
