### ISSUE TITLE
Field renamings tied to type instead of instance

### ISSUE THREAD

**Issue by lloydmeta** [scalalandio/chimney#75]
Firstly, thanks for writing this awesome lib, I think it serves ~95% of our use cases for writing things manually :)

One thing that might be useful is to be able define field renamings that aren't tied to a specific instance of a type.  I think we can currently do renamings via `.into` from the DSL, and it's powered by `TransformInto`, but it seems to be tied to a specific `source: From`.

https://github.com/scalalandio/chimney/blob/f6f0844307090365fe987036d3af2bb5060e519e/chimney/src/main/scala/io/scalaland/chimney/dsl.scala#L18-L20

In my mind, it might be nice to have something like

```scala
import io.scalaland.chimney.dsl._

case class A(firstName: String, lastName: String, age: Int)
case class B(nameFirst: String, nameLast: String, age: Int)

// Fail compilation if not all required re-mappings are complete
// Note that age does not need to be re-mapped, as is the case with existing `.into`
implicit val aToBTransformer: Transformer[A, B] = TransformerInto
  .derive[A, B]
  .withFieldRenamed(_.firstName, _.nameFirst)
  .withFieldRenamed(_.lastName, _.nameLast)
  .toTransformer

val a = A(firstName = "joe", lastName = "Blow", age = 10)
val b = a.transformInto[B]
```

My current work-around is to define a method that uses the DSL, but something on the type-level might be nice so it's (1) more easily reusable, and (2) can be picked up when deriving other `Transformer`s that nest `A` and `B` (e.g. `Transformer[ContainsA, ContainsB]`)

```scala
def aToBTransform(a: A): B = {
  a.into[B]
    .withFieldRenamed(_.firstName, _.nameFirst)
    .withFieldRenamed(_.lastName, _.nameLast)
    .transform
}
```

**Comment by krzemin** [comment]
Hey, did you try lifting your custom function to implicit `Transformer[A, B]` instance?

```scala
implicit val  aToBTransform: Transformer[A, B] = new Transformer[A, B] {
  def transform(a: A): B = {
    a.into[B]
      .withFieldRenamed(_.firstName, _.nameFirst)
      .withFieldRenamed(_.lastName, _.nameLast)
      .transform
  }
}
```

Having such instance in implicit scope, macro should pick it up when expanding some nested transformation (i.e. `Transformer[ContainsA, ContainsB]`).

**Comment by lloydmeta** [comment]
🤦‍♂️ @krzemin great idea; that totally slipped my mind. Closing since this issue works ([Scastie demo](https://scastie.scala-lang.org/lloydmeta/O0NcZy4BTAKCnzyaHq2jnw/1)).

Thanks again!
