### ISSUE TITLE
Rename w/ transform?

### ISSUE THREAD

**Issue by lloydmeta** [scalalandio/chimney#76]
I was thinking it might be nice to have a version of `withFieldRenamed` that would rename + take an in-scope `Transformer` to rename and transform at the same time; currently you would need to do `withFieldComputed`

e.g.

```scala
case class InternalTicket(createdAt: DateTime)

case class ExternalTicket(createdAtMillis: Long)

implicit val jodaDateTimeToLong = new Transformer[DateTime, Long] {
  def transform(dt: DateTime): Long = dt.toInstant.getMillis
}

val externalTicket = InternalTicket(DateTime.now).into[ExternalTicket]
  .withFieldRenamed(_.createdAt, _.createdAtMillis)
```

Currently, it seems like we need to do

```scala
val externalTicket = InternalTicket(DateTime.now).into[ExternalTicket]
  .withFieldComputed(_.createdAtMillis, _.toInstant.getMillis)
```

which is marginally longer for this small example, but can get repetitive if there are more fields.

I also tried with an in-scope implicit conversion, but it doesn't get picked up.

As with my previous issue, it might be that this is already possible, but it doesn't seem like it 😅

**Comment by krzemin** [comment]
Well, that seems to be pretty useful and in par with the philosophy of the library 👍 

For now, when renaming from `Foo(a: T1)` to `Bar(b: T2)`, we require types `T1` and `T2` to be the same. But we may generalize this behavior and perform recursive expansion of transformer between T1 and T2, which would cover your case when already having an instance in implicit scope.

It also should be quite easy to implement.
