### ISSUE TITLE
add automatic field renaming according to custom function or popular conventions

### ISSUE THREAD

**Issue by kmikulski** [scalalandio/chimney#89]
It might be useful to consider adding a method that automatically renames all fields of a class according to provided `f: String => String`, something along these lines:
```
case class MyDTO(my_string_field: String, my_int_field: Int)
case class MyEntity(myStringField: String, myIntField: Int)

def rename(s: String) = {
  val words = s.split("_").toList
  (words.head :: words.tail.map(_.capitalize)).mkString
}

MyDTO("abc", 1).into[MyEntity].withFieldsAutorenamed(rename).transform
```
If running a user-provided function in compile time turns out to be impossible or we deem it too dangerous, perhaps we could support transitions between the common case styles?

**Comment by krzemin** [comment]
The problem with function provided by the user is that either (1) we sacrifice compile-time type safety and run the function in runtime allowing for runtime exceptions, or (2) we must be somehow able to run this function in compile time.

From my perspective (1) is no-go zone as it would diminish strong guarantees provided by the library. When it comes to (2), it doesn't either seem to be technically possible as it would require taking a program that is being compiled and run it during the compilation.

What we could do instead is to provide builtin support for `camelCase` and `snake_case` naming styles - something like:

```
MyDTO("abc", 1)
  .into[MyEntity]
  .withNamingConvention(Naming.SnakeCase, Naming.CamelCase)
  .transform
```

I'm keen to accept PRs that provides support for such conventions.

**Comment by MateuszKubuszok** [comment]
Added in 1.0.0-M3
