### ISSUE TITLE
Add example of ADTs with more than enums

### ISSUE THREAD

**Issue by kubukoz** [scalalandio/chimney#97]
The current example:

```scala
sealed trait Color
object Color {
  case object Red extends Color
  case object Green extends Color
  case object Blue extends Color
}

sealed trait Channel
object Channel {
  case object Alpha extends Channel
  case object Blue extends Channel
  case object Green extends Channel
  case object Red extends Channel
}
```

doesn't show that it's possible to transform if you have a more complex ADT with class leaves. That could be improved :)

**Comment by krzemin** [comment]
The example from tests can be used:

https://github.com/scalalandio/chimney/blob/master/chimney/src/test/scala/io/scalaland/chimney/examples/Shapes.scala

**Comment by MateuszKubuszok** [comment]
I think the current documentation covers this request :)
