### ISSUE TITLE
withFieldRenamed and withFieldComputed/withFieldConst have opposite input parameter orders

### ISSUE THREAD

**Issue by Woodz** [scalalandio/chimney#99]
`def withFieldRenamed[T, U](selectorFrom: From => T, selectorTo: To => U)` uses `From` in the first argument and `To` in the second, whereas

`def withFieldConst[T, U](selector: To => T, value: U)` and `def withFieldComputed[T, U](selector: To => T, map: From => U)` use `To` in the first argument and `From` in the second.

To improve the consistency of the API, when a breaking change needs to be made I suggest swapping the parameter order of `withFieldRenamed` so that all methods take the `To` type in the first parameter and `From` in the second. This would read a lot nicer as this would align with manual field assignment (e.g. `To.field1` = `From.field2`)

**Comment by krzemin** [comment]
Let's take a brief look at both signatures:
```scala
def withFieldComputed[T, U](selector: To => T, map: From => U): TransformerInto[From, To, _]
def withFieldRenamed[T, U](selectorFrom: From => T, selectorTo: To => U): TransformerInto[From, To, _]
```

Let's forget argument names (they're not important) and return types (cause they're the same):
```scala
def withFieldComputed[T, U](_: To => T, _: From => U)
def withFieldRenamed[T, U](_: From => T, _: To => U)
```

If we apply your proposal, we obtain:
```scala
def withFieldComputed[T, U](_: To => T, _: From => U)
def withFieldRenamed[T, U](_: To => U, _: From => T)
```

Cause order of type parameters don't matter in this context, both signatures are actually the same:
```scala
def withFieldComputed[T, U](_: To => T, _: From => U)
def withFieldRenamed[T, U](_: To => T, _: From => U)
```
(however `withFieldRenamed` will accept only selectors in form of `_.field` for both parameters, but `withFieldComputed` any functional expression for the second parameter) 

So `withFieldRenamed` would effectively become a functional subset of `withFieldComputed`. That change doesn't make sense to me, especially if it's justified only by API "consistency". 

I'd say that keeping both operations separated (as it is now) is justified by 2 reasons:
- it leads to code that is semantically distinguished and read in a different way, e.g.:
    - `withFieldComputed(_.foo, fun)` reads as "please compute value of `foo` field using function `fun`"
    - `withFieldRenamed(_.foo, _.bar)` reads as "please rename field `foo` to `bar`"
- `withFieldRenamed` may be a little bit more performant in runtime, as it generate a little bit more effective code
